dist: xenial

language: python

cache: pip

python: 3.8

services:
  - postgresql

addons:
  postgresql: "10"

env:
  global:
  - DJANGO_SETTINGS_MODULE=openpersonen.conf.ci
  - SECRET_KEY=dummy
  - DB_PASSWORD=
  - DB_USER=postgres

install:
  - pip install -r requirements/dev.txt
  - pip install codecov
  - npm ci
  - npm run build

jobs:
  include:
    # Run jobs in parallel in stage Tests
    - stage: "Tests"
      name: "Unit tests"
      script:
        - python src/manage.py collectstatic --noinput --link
        - coverage run src/manage.py test src

    - name: "Code imports"
      before_install: skip
      install:
        - pip install isort
      before_script: skip
      script: isort . --check-only --diff

    - name: "Code format"
      before_install: skip
      install:
        - pip install black
      before_script: skip
      script: black --check src --diff

    - name: "Open API Check"
      before_install: skip
      install:
        - pip install -r requirements/ci.txt
        - npm install -g swagger2openapi@5.2.5
        - npm install -g openapi-diff@0.23.3
      before_script: skip
      script:
        - generate_schema
        - wget https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/8afe4f2b3f89059b03d484b99647f0ec26eb55b6/specificatie/genereervariant/openapi.yaml
        - openapi-diff openapi.yaml src/openapi.yaml

    - stage: "Docker image"
      name: Docker image build
      services:
        - docker
      install: skip
      script: docker build .
      deploy:
        - provider: script
          script: bin/docker_push.sh latest
          on:
            branch: master

        - provider: script
          script: bin/docker_push.sh $TRAVIS_TAG
          on:
            tags: true


after_success:
  - codecov
