version: '3'

services:
  busybox:
    volumes:
      - private_media:/private-media
  web:
    volumes:
      - private_media:/app/private-media
  nginx:
    volumes:
      - private_media:/private-media

volumes:
  private_media:
