from .aangaan_huwelijk_partnerschap import *  # noqa
from .datum import *  # noqa
from .geboorte import *  # noqa
from .gezags_verhouding import *  # noqa
from .in_onderzoek import *  # noqa
from .ingeschreven_personen import *  # noqa
from .kiesrecht import *  # noqa
from .kind import *  # noqa
from .naam import *  # noqa
from .nationaliteit import *  # noqa
from .opschorting_bijhouding import *  # noqa
from .ouder import *  # noqa
from .overlijden import *  # noqa
from .partner import *  # noqa
from .persoon import *  # noqa
from .verblijf_buitenland import *  # noqa
from .verblijf_plaats import *  # noqa
from .verblijfs_titel import *  # noqa
from .waarde import *  # noqa
