# Generated by Django 2.2.15 on 2020-12-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RedenCodeAndOmschrijving",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("omschrijving", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=1)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
