from .aangaanhuwelijkpartnerschap import *  # noqa
from .codeenomschrijving import *  # noqa
from .datum import *  # noqa
from .geboorte import *  # noqa
from .gezagsverhouding import *  # noqa
from .ingeschrevenpersonen import *  # noqa
from .inonderzoek import *  # noqa
from .kiesrecht import *  # noqa
from .kind import *  # noqa
from .naam import *  # noqa
from .nationaliteit import *  # noqa
from .opschortingbijhouding import *  # noqa
from .ouder import *  # noqa
from .overlijden import *  # noqa
from .partner import *  # noqa
from .persoon import *  # noqa
from .verblijfbuitenland import *  # noqa
from .verblijfplaats import *  # noqa
from .verblijfstitel import *  # noqa
