from .aanduiding_bij_huisnummer import AanduidginBijHuisnummerChoices
from .aanduiding_bijzonder_nederlanderschap import AanduidingBijzonderNederlanderschapChoices
from .aanduiding_naamgebruik import AanduidingNaamgebruikChoices
from .functie_adres import FunctieAdresChoices
from .geslachtsaanduiding import GeslachtsaanduidingChoices
from .indicatie_gezag_minderjarige import IndicatieGezagMinderjarigeChoices
from .reden_opschorting_bijhouding import RedenOpschortingBijhoudingChoices
