# Generated by Django 2.2.15 on 2020-09-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gezagsverhouding_inschrijving_kiesrecht_kind_nationaliteit_ouder_overlijden_partnerschap_persoon_rei'),
    ]

    operations = [
        migrations.AddField(
            model_name='stufbgclient',
            name='certificate',
            field=models.FileField(null=True, upload_to='certificate/'),
        ),
    ]
