# Generated by Django 2.2.15 on 2020-10-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StufBGClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontvanger_organisatie', models.CharField(max_length=200, verbose_name='organisatie')),
                ('ontvanger_administratie', models.CharField(max_length=200, verbose_name='administratie')),
                ('ontvanger_applicatie', models.CharField(max_length=200, verbose_name='applicatie')),
                ('ontvanger_gebruiker', models.CharField(max_length=200, verbose_name='gebruiker')),
                ('zender_organisatie', models.CharField(max_length=200, verbose_name='organisatie')),
                ('zender_administratie', models.CharField(max_length=200, verbose_name='administratie')),
                ('zender_applicatie', models.CharField(max_length=200, verbose_name='applicatie')),
                ('zender_gebruiker', models.CharField(max_length=200, verbose_name='gebruiker')),
                ('url', models.URLField(verbose_name='url')),
                ('user', models.CharField(max_length=200, verbose_name='user')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('certificate', models.FileField(upload_to='certificate/')),
                ('certificate_key', models.FileField(help_text='Private key for the certificate', upload_to='certificate/')),
            ],
            options={
                'verbose_name': 'Stuf BG Client',
            },
        ),
    ]
