# Generated by Django 2.2.15 on 2021-04-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stufbg', '0003_auto_20201117_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stufbgclient',
            name='password',
            field=models.CharField(blank=True, help_text='Password to access the server', max_length=200, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='stufbgclient',
            name='url',
            field=models.URLField(blank=True, help_text='Url of the server this client will make requests to', verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='stufbgclient',
            name='user',
            field=models.CharField(blank=True, help_text='Username to access the server', max_length=200, verbose_name='user'),
        ),
    ]
