# Generated by Django 2.2.15 on 2021-04-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stufbg", "0004_auto_20210423_1630"),
        ("stufbg", "0004_auto_20210416_0937"),
    ]

    operations = []
