name: Python CI

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  black:
    name: Check code formatting with black
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install -r requirements/ci.txt
          pip install black
      - name: Run black
        run: |
          black --check src --diff
