name: Isort

## Run this workflow every time a new commit pushed to your repository
#on:
#  push:
#    branches:
#      - master
#    tags:
#    paths:
#      - '**.py'
#  pull_request:
#    paths:
#      - '**.py'
# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  isort:
    name: Check quickstart steps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          wget https://raw.githubusercontent.com/maykinmedia/open-personen/master/docker-compose-quickstart.yml -O docker-compose.yml
          docker-compose up -d
      - name: Run openapi check
        run: |
          wget http://localhost:8000/api/ingeschrevenpersonen/999990676
